/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.lanchonete;

/**
 *
 * @author GABRIELASILVADAROSA
 */
public class LanchoneteInterface extends javax.swing.JFrame {

    /**
     * Creates new form LanchoneteInterface
     */
    public LanchoneteInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        chkMonstro = new javax.swing.JCheckBox();
        chkArepas = new javax.swing.JCheckBox();
        chkDogao = new javax.swing.JCheckBox();
        chkPastel = new javax.swing.JCheckBox();
        lblLanches = new javax.swing.JLabel();
        lblBebidas = new javax.swing.JLabel();
        chkCoca = new javax.swing.JCheckBox();
        chkSucoUva = new javax.swing.JCheckBox();
        chkAgua = new javax.swing.JCheckBox();
        chkH2O = new javax.swing.JCheckBox();
        lblDoces = new javax.swing.JLabel();
        chkTrident = new javax.swing.JCheckBox();
        chkHalls = new javax.swing.JCheckBox();
        chkAlfajor = new javax.swing.JCheckBox();
        chkTrufa = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCalular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 164, 126));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        chkMonstro.setBackground(new java.awt.Color(255, 153, 51));
        chkMonstro.setForeground(new java.awt.Color(0, 0, 0));
        chkMonstro.setText("X Monstro - R$ 31.00");
        chkMonstro.setContentAreaFilled(false);

        chkArepas.setBackground(new java.awt.Color(255, 153, 51));
        chkArepas.setForeground(new java.awt.Color(0, 0, 0));
        chkArepas.setText("Arepas do Edu R$ 15,00");
        chkArepas.setContentAreaFilled(false);

        chkDogao.setBackground(new java.awt.Color(255, 153, 51));
        chkDogao.setForeground(new java.awt.Color(0, 0, 0));
        chkDogao.setText("Dogão  R$ 12,00");
        chkDogao.setContentAreaFilled(false);

        chkPastel.setBackground(new java.awt.Color(255, 153, 51));
        chkPastel.setForeground(new java.awt.Color(0, 0, 0));
        chkPastel.setText("Pastel R$ 10,00");
        chkPastel.setContentAreaFilled(false);

        lblLanches.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLanches.setForeground(new java.awt.Color(75, 46, 30));
        lblLanches.setText("Lanches");

        lblBebidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBebidas.setForeground(new java.awt.Color(75, 46, 30));
        lblBebidas.setText("Bebidas");

        chkCoca.setBackground(new java.awt.Color(255, 153, 51));
        chkCoca.setForeground(new java.awt.Color(0, 0, 0));
        chkCoca.setText("Coquinha 350ml R$7,00");
        chkCoca.setContentAreaFilled(false);

        chkSucoUva.setBackground(new java.awt.Color(255, 153, 51));
        chkSucoUva.setForeground(new java.awt.Color(0, 0, 0));
        chkSucoUva.setText("Suco de Uva R$ 5,00");
        chkSucoUva.setContentAreaFilled(false);

        chkAgua.setBackground(new java.awt.Color(255, 153, 51));
        chkAgua.setForeground(new java.awt.Color(0, 0, 0));
        chkAgua.setText("Água R$ 4,00");
        chkAgua.setContentAreaFilled(false);

        chkH2O.setBackground(new java.awt.Color(255, 153, 51));
        chkH2O.setForeground(new java.awt.Color(0, 0, 0));
        chkH2O.setText("H20 R$ 8,00");
        chkH2O.setContentAreaFilled(false);

        lblDoces.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDoces.setForeground(new java.awt.Color(75, 46, 30));
        lblDoces.setText("Doces");

        chkTrident.setBackground(new java.awt.Color(255, 153, 51));
        chkTrident.setForeground(new java.awt.Color(0, 0, 0));
        chkTrident.setText("Trident R$ 3,00");
        chkTrident.setContentAreaFilled(false);

        chkHalls.setBackground(new java.awt.Color(255, 153, 51));
        chkHalls.setForeground(new java.awt.Color(0, 0, 0));
        chkHalls.setText("Halls R$ 2,00");
        chkHalls.setContentAreaFilled(false);

        chkAlfajor.setBackground(new java.awt.Color(255, 153, 51));
        chkAlfajor.setForeground(new java.awt.Color(0, 0, 0));
        chkAlfajor.setText("Alfajor R$ 8,00");
        chkAlfajor.setContentAreaFilled(false);

        chkTrufa.setBackground(new java.awt.Color(255, 153, 51));
        chkTrufa.setForeground(new java.awt.Color(0, 0, 0));
        chkTrufa.setText("Trufa R$ 8,00");
        chkTrufa.setContentAreaFilled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 46, 30));
        jLabel3.setText("Confira nosso Cardápio!");

        jSeparator1.setBackground(new java.awt.Color(166, 123, 91));

        btnCalular.setBackground(new java.awt.Color(139, 94, 60));
        btnCalular.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnCalular.setText("Calcular Total");
        btnCalular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalularActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(139, 94, 60));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblResultado.setBackground(new java.awt.Color(75, 46, 30));
        lblResultado.setForeground(new java.awt.Color(166, 123, 91));
        lblResultado.setText("Total: 0.00");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblLanches)
                .addGap(131, 131, 131)
                .addComponent(lblBebidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDoces)
                .addGap(74, 74, 74))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chkMonstro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkArepas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkDogao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkPastel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSucoUva, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkH2O, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkCoca))
                                .addGap(36, 36, 36)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkTrident, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkAlfajor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkTrufa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkHalls, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel3))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(btnCalular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(83, 83, 83)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(lblResultado)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanches)
                    .addComponent(lblBebidas)
                    .addComponent(lblDoces))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMonstro)
                    .addComponent(chkCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTrident))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkArepas)
                    .addComponent(chkAgua)
                    .addComponent(chkHalls))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDogao)
                    .addComponent(chkSucoUva)
                    .addComponent(chkAlfajor))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPastel)
                    .addComponent(chkH2O)
                    .addComponent(chkTrufa))
                .addGap(34, 34, 34)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalular)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(lblResultado)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lanchonete ");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DO");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SENAC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalularActionPerformed
        
        
        double total = 0;
        
        //LANCHES
        if(chkMonstro.isSelected()) total +=31;
        if(chkArepas.isSelected()) total += 15;
        if(chkDogao.isSelected()) total += 12;
        if(chkPastel.isSelected()) total += 10;
        
        //BEBIBAS
        if(chkCoca.isSelected()) total += 7;
        if(chkAgua.isSelected()) total += 4;
        if(chkSucoUva.isSelected()) total += 5;
        if(chkH2O.isSelected()) total += 8;
        
        //DOCES
        if(chkTrident.isSelected()) total += 3;
        if(chkHalls.isSelected()) total += 2;
        if(chkAlfajor.isSelected())total +=8;
        if(chkTrufa.isSelected()) total +=8;
        
        lblResultado.setText(String.format("Total: R$ %.2f", total));
        
        if(total == 0){
            lblResultado.setForeground(new java.awt.Color(200,0,0));
            lblResultado.setText("Nenhum item selecionado!");
        }
        else if(total<0)
        {
        lblResultado.setForeground(new java.awt.Color(0,100,0));
        }
        else if(total <=25)
        {
         lblResultado.setForeground(new java.awt.Color(0,128,255));
        }
        else
        {
         
            lblResultado.setForeground(new java.awt.Color(255,128,9));
            lblResultado.setText(String.format("Pedido completo! Total: R$%.2f", total));
        }
    }//GEN-LAST:event_btnCalularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       chkMonstro.setSelected(false);
       chkAlfajor.setSelected(false);
       chkArepas.setSelected(false);
       chkCoca.setSelected(false);
       chkDogao.setSelected(false);
       chkH2O.setSelected(false);
       chkTrufa.setSelected(false);
       chkTrident.setSelected(false);
       chkPastel.setSelected(false);
       chkSucoUva.setSelected(false);
       chkMonstro.setSelected(false);
       chkAgua.setSelected(false);
       
       lblResultado.setText("Total: R$ 0.00");
       lblResultado.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LanchoneteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LanchoneteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LanchoneteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LanchoneteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LanchoneteInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JCheckBox chkAgua;
    private javax.swing.JCheckBox chkAlfajor;
    private javax.swing.JCheckBox chkArepas;
    private javax.swing.JCheckBox chkCoca;
    private javax.swing.JCheckBox chkDogao;
    private javax.swing.JCheckBox chkH2O;
    private javax.swing.JCheckBox chkHalls;
    private javax.swing.JCheckBox chkMonstro;
    private javax.swing.JCheckBox chkPastel;
    private javax.swing.JCheckBox chkSucoUva;
    private javax.swing.JCheckBox chkTrident;
    private javax.swing.JCheckBox chkTrufa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBebidas;
    private javax.swing.JLabel lblDoces;
    private javax.swing.JLabel lblLanches;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
