
import com.sun.source.tree.CatchTree;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GABRIELASILVADAROSA
 */
public class InterfaceBanco extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceBanco
     */
    public InterfaceBanco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnConverter = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        valorR$ = new javax.swing.JLabel();
        EscolhaConversao = new javax.swing.JComboBox<>();
        seleçãoConversao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Conversor de Moedas Mundial");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        btnConverter.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        btnConverter.setText("Converter");
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });

        lblResultado.setBackground(new java.awt.Color(255, 255, 255));
        lblResultado.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 255));
        lblResultado.setText("Você terá :");

        valorR$.setBackground(new java.awt.Color(255, 255, 255));
        valorR$.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        valorR$.setForeground(new java.awt.Color(255, 255, 255));
        valorR$.setText("Digite aqui seu valor em R$");

        EscolhaConversao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar(USD)", "Euros(EUR)", "Peso Argentino(ARS)", " " }));
        EscolhaConversao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolhaConversaoActionPerformed(evt);
            }
        });

        seleçãoConversao.setBackground(new java.awt.Color(255, 255, 255));
        seleçãoConversao.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        seleçãoConversao.setForeground(new java.awt.Color(255, 255, 255));
        seleçãoConversao.setText("Selecione o tipo de conversão");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleçãoConversao)
                            .addComponent(valorR$)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EscolhaConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblResultado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(66, 66, 66)
                .addComponent(valorR$)
                .addGap(24, 24, 24)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleçãoConversao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EscolhaConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnConverter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(lblResultado)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
      
    }//GEN-LAST:event_txtValorActionPerformed

    private void EscolhaConversaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolhaConversaoActionPerformed
        
    }//GEN-LAST:event_EscolhaConversaoActionPerformed

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed
        try{
        
        String valorStr = txtValor.getText().trim().replace(",", ".");
        
        if (valorStr.isEmpty())
        {
        lblResultado.setText("Por favor, digite um valor.");
        lblResultado.setForeground(new java.awt.Color(255, 255, 255));
        return;
        }
        
        
        //converter o valor pra decimal
        double valor = Double.parseDouble(valorStr);  
        
        //se o valor for maior que zero
        if(valor <= 0)
        {
            lblResultado.setText("O valor deve ser maior que zero.");
            lblResultado.setForeground(new java.awt.Color(255, 255, 255));
            return;
        }
        
        //pega a opçao da box que eu coloquei 
        String tipo = (String)EscolhaConversao.getSelectedItem();
        
        //aqui é pra guardar o resultado e a cor kk
        double resultado = 0;
        java.awt.Color cor;

        
       
        // aqui pa fazer a conversão
        
      if(tipo.equals("Dolar(USD)"))
    {
    resultado = valor / 5.60;
    lblResultado.setForeground(new java.awt.Color(0,0,0));
    }
      
    else if(tipo.equals("Euros(EUR)")) 
    {
    resultado = valor / 6.10;
    lblResultado.setForeground(new java.awt.Color(0,0,0));
    }
    
    else if(tipo.equals("Peso Argentino(ARS)")) 
    {
    resultado = valor / 0.030;
    lblResultado.setForeground(new java.awt.Color(0,0,0));
    }

        else{
            lblResultado.setText("Selecione uma opção válida");
            lblResultado.setForeground(new java.awt.Color(0,0,0));
        }
      
                
          lblResultado.setText(String.format("Você terá: %.2f", resultado));
  
    } 
        catch(NumberFormatException e )
        {
        lblResultado.setText("Entrada Inválida! Use números, ex: 100 ou 100.50.");
        }
            
    }//GEN-LAST:event_btnConverterActionPerformed
   
    
  
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EscolhaConversao;
    private javax.swing.JButton btnConverter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel seleçãoConversao;
    private javax.swing.JTextField txtValor;
    private javax.swing.JLabel valorR$;
    // End of variables declaration//GEN-END:variables
}
