



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GABRIELASILVADAROSA
 */
public class Gabi extends javax.swing.JFrame {

    /**
     * Creates new form Gabi
     */
    public Gabi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        altura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Peso = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Altura = new javax.swing.JTextPane();
        btnCalular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setText("Calculadora IMC");

        peso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        peso.setForeground(new java.awt.Color(255, 255, 255));
        peso.setText("Peso");

        altura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        altura.setForeground(new java.awt.Color(255, 255, 255));
        altura.setText("Altura");

        jScrollPane1.setViewportView(Peso);

        jScrollPane2.setViewportView(Altura);

        btnCalular.setBackground(new java.awt.Color(204, 204, 255));
        btnCalular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalular.setText("Calcular");
        btnCalular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalularActionPerformed(evt);
            }
        });

        lblResultado.setText("Resultado:");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(altura))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(peso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(peso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(altura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnCalular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(lblResultado)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalularActionPerformed
                                                                                
    try {  
        // Pega o texto digitado nos campos Peso e Altura
        String PesoStr = Peso.getText().trim().replace(",", ".");
        String AlturaStr = Altura.getText().trim().replace(",", ".");

        // Verifica se os campos estão vazios
        if (PesoStr.isEmpty() || AlturaStr.isEmpty()) {
            lblResultado.setText("Por favor, preencha peso e altura.");
            lblResultado.setForeground(new java.awt.Color(200, 0, 0));
            return;  
        }

        // Converte texto para número
        double peso = Double.parseDouble(PesoStr);
        double altura = Double.parseDouble(AlturaStr);

        // Verifica se os valores são válidos
        if (peso <= 0 || altura <= 0) {
            lblResultado.setText("Os valores devem ser maiores que zero.");
            lblResultado.setForeground(new java.awt.Color(200, 0, 0));
            return;
        }
        
        double imc = peso/(peso*altura);
        
        String Classificacao;
        java.awt.Color cor;
        
        if(imc<18.5)
        {
            Classificacao = "Abaixo do peso";
            cor = new java.awt.Color(0,102,204);
        }

        else if
            (imc<25)
        {
            
           Classificacao = "Peso normal";
           cor = new java.awt.Color(0, 128, 0);
           
        }
        
        
        else if (imc <30 )
        {
            
         Classificacao = "Sobrepeso";
         cor = new java.awt.Color(255, 140, 0);
         
        }
        
         else if (imc<35)
        {
            
        Classificacao = "Obesidade I";
        cor = new java.awt.Color(220,20,60);
        
        }  
         
         else if (imc<40)
        {
            
        Classificacao = "Obesidade II";
        cor = new java.awt.Color(178,34,34);
        
        } 

        else 
             
        { 
            Classificacao = "Obesidade III";
            cor = new java.awt.Color(139,0,0);
        }
        
        lblResultado.setText(String.format("imc: %.2f - %S", imc, Classificacao));
        lblResultado.setForeground(cor);
        
    }
    
    
    catch(NumberFormatException e)
    {
    lblResultado.setText("Entrada Inválida!Use números, ex:70 e 1.70.");
    lblResultado.setForeground(new java.awt.Color(200,0,0));
    
    }
    
    
    }//GEN-LAST:event_btnCalularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Peso.setText("");
        Altura.setText("");
        lblResultado.setText("-");
        lblResultado.setForeground(new java.awt.Color(0,0,0));
        Peso.requestFocus();

    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gabi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Altura;
    private javax.swing.JTextPane Peso;
    private javax.swing.JLabel altura;
    private javax.swing.JButton btnCalular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel peso;
    // End of variables declaration//GEN-END:variables
}
